In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('zara.csv', delimiter=';')

In [3]:
df.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [4]:
df.nunique().head(20)

Product ID          252
Product Position      3
Promotion             2
Product Category      1
Seasonal              2
Sales Volume        234
brand                 1
url                 228
sku                 228
name                194
description         221
price                28
currency              1
scraped_at          229
terms                 5
section               2
dtype: int64

In [5]:
# Drop useless columns
df_cleaned = df.drop(columns=['Product Category', 'brand', 'sku', 'currency', 'description', 'url', 'scraped_at'])
# binary encoding
df_cleaned.replace({'section': {'MAN': False, 'WOMAN': True}}, inplace=True)
df_cleaned['section'] = df_cleaned['section'].astype(bool)

df_cleaned.replace({'Seasonal': {'No': False, 'Yes': True}}, inplace=True)
df_cleaned['Seasonal'] = df_cleaned['Seasonal'].astype(bool)

df_cleaned.replace({'Promotion': {'No': False, 'Yes': True}}, inplace=True)
df_cleaned['Promotion'] = df_cleaned['Promotion'].astype(bool)
# one-hot encoding
df_position_dummies = pd.get_dummies(df['Product Position'], dtype=bool)
df_cleaned.drop(columns=['Product Position'], inplace=True)
df_cleaned = pd.concat([df_cleaned, df_position_dummies], axis=1)

df_terms_dummies = pd.get_dummies(df['terms'], dtype=bool)
df_cleaned.drop(columns=['terms'], inplace=True)
df_cleaned = pd.concat([df_cleaned, df_terms_dummies], axis=1)

df_cleaned.head()

C:\Users\jefgr\AppData\Local\Temp\ipykernel_19128\2940287289.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cleaned.replace({'section': {'MAN': False, 'WOMAN': True}}, inplace=True)
C:\Users\jefgr\AppData\Local\Temp\ipykernel_19128\2940287289.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cleaned.replace({'Seasonal': {'No': False, 'Yes': True}}, inplace=True)
C:\Users\jefgr\AppData\Local\Temp\ipykernel_19128\2940287289.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cleaned.replace({'Promotion': {'No': False, 'Yes': True}}, inplace=True)

,Product ID,Promotion,Seasonal,Sales Volume,name,price,section,Aisle,End-cap,Front of Store,jackets,jeans,shoes,sweaters,t-shirts
0,185102,False,False,2823,BASIC PUFFER JACKET,19.99,False,True,False,False,True,False,False,False,False
1,188771,False,False,654,TUXEDO JACKET,169.00,False,True,False,False,True,False,False,False,False
2,180176,True,True,2220,SLIM FIT SUIT JACKET,129.00,False,False,True,False,True,False,False,False,False
3,112917,True,True,1568,STRETCH SUIT JACKET,129.00,False,True,False,False,True,False,False,False,False
4,192936,False,True,2942,DOUBLE FACED JACKET,139.00,False,False,True,False,True,False,False,False,False

In [6]:
df_cleaned.to_csv("zara_cleaned.csv", index=False)